from user_service.lib.exceptions import BaseException
